/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'angus' at '20.10.16 16:39' with Gradle 2.10
 *
 * @author angus, @date 20.10.16 16:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
